from dataclasses import dataclass


@dataclass(frozen=True)
class Task:
    task_id: str
    image: str
    runtime: dict
    category: str
    error_type: str
    summary: str
    context: str
    setup: str
    failing_command: str
    failed_approaches: tuple[str, ...]
    fix_command: str
    verification_command: str
    root_cause: str
    steps: tuple[str, ...]
    tags: tuple[str, ...]


TASKS = (
    Task("python-distutils-312", "python:3.12.4", {"name": "python", "version": "3.12.4"}, "dependency", "ModuleNotFoundError", "A Python 3.12 project imports distutils even though the standard-library module was removed.", "Running a legacy setup script on Python 3.12.", "", "python -S -c 'import distutils'", ("python -S -m pip install distutils==999.0.0", "apt-get install -y python3.12-distutils"), "python -m pip install -q setuptools", "python -c 'import setuptools._distutils as distutils; print(distutils.__name__)'", "Python 3.12 removed distutils; legacy code must use the setuptools compatibility module or a modern build backend.", ("Install setuptools in the active environment.", "Import the compatibility implementation supplied by setuptools.",), ("python", "python3.12", "distutils", "pip")),
    Task("pip-pep668-ubuntu", "ubuntu:24.04", {"name": "python", "version": "3.12.3"}, "dependency", "externally-managed-environment", "Ubuntu 24.04 refuses a system pip install because the interpreter is externally managed.", "Installing an application dependency on a fresh Ubuntu host.", "apt-get update -qq && apt-get install -y -qq python3 python3-pip python3-venv", "python3 -m pip install requests", ("python3 -m pip install --user requests", "python3 -m pip install --user requests --no-cache-dir"), "python3 -m venv /tmp/app-venv && /tmp/app-venv/bin/pip install -q requests", "/tmp/app-venv/bin/python -c 'import requests; print(requests.__version__)'", "PEP 668 marks the OS interpreter as managed by the distribution, so application packages belong in a virtual environment.", ("Create an isolated virtual environment.", "Install the dependency with that environment's pip.",), ("python", "ubuntu", "pip", "pep668")),
    Task("node-openssl-md4", "node:18.20.4", {"name": "node", "version": "18.20.4"}, "runtime", "ERR_OSSL_EVP_UNSUPPORTED", "Node 18 rejects an old webpack-style MD4 hash because it uses OpenSSL 3.", "Building a legacy JavaScript bundle on Node 18.", "", "node -e \"require('crypto').createHash('md4').update('x').digest('hex')\"", ("node -e \"require('crypto').createHash('md4').update('x').digest('hex')\"", "node -e \"require('crypto').createHash('md4').update('y').digest('hex')\""), "NODE_OPTIONS=--openssl-legacy-provider node -e \"require('crypto').createHash('md4').update('x').digest('hex')\"", "NODE_OPTIONS=--openssl-legacy-provider node -e \"require('crypto').createHash('md4').update('x').digest('hex'); console.log('hash ok')\"", "Node 17 and later link OpenSSL 3, which disables MD4 unless the legacy provider is explicitly enabled.", ("Set NODE_OPTIONS for the legacy build process.", "Prefer upgrading the bundler to remove the MD4 dependency.",), ("node", "openssl", "webpack", "node18")),
    Task("npm-peer-deps", "node:18.20.4", {"name": "node", "version": "18.20.4"}, "dependency", "ERESOLVE", "npm refuses to install React packages whose peer dependency ranges do not agree.", "Installing a package set with React 17 and a React 18 renderer.", "mkdir -p /tmp/app && cd /tmp/app && printf '{\"private\":true}\n' > package.json", "cd /tmp/app && npm install --no-audit --no-fund react@17.0.2 react-dom@18.2.0", ("cd /tmp/app && npm install --no-audit --no-fund react@17.0.2 react-dom@18.2.0 --package-lock=false", "cd /tmp/app && npm install --no-audit --no-fund react@17.0.2 react-dom@18.2.0 --omit=optional"), "cd /tmp/app && npm install --no-audit --no-fund react@17.0.2 react-dom@17.0.2", "cd /tmp/app && node -e \"const r=require('react'); const d=require('react-dom'); if(r.version !== '17.0.2') process.exit(1); console.log(r.version, d.version)\"", "react-dom 18 requires React 18 as a peer; aligning both packages removes the resolver conflict instead of suppressing it.", ("Pin compatible major versions.", "Install again without bypass flags.",), ("node", "npm", "react", "peer-dependencies")),
    Task("git-safe-directory", "ubuntu:24.04", {"name": "git", "version": "2.43.0"}, "permissions", "git dubious ownership", "Git refuses to operate in a repository owned by another user.", "An agent runs Git in a workspace prepared by a different container user.", "apt-get update -qq && apt-get install -y -qq git && mkdir -p /tmp/repo /tmp/nobody-home && git -C /tmp/repo init -q", "HOME=/tmp/nobody-home su nobody -s /bin/sh -c 'git -C /tmp/repo status'", ("HOME=/tmp/nobody-home su nobody -s /bin/sh -c 'git -C /tmp/repo status'", "HOME=/tmp/nobody-home su nobody -s /bin/sh -c 'git -C /tmp/repo status'"), "su nobody -s /bin/sh -c 'HOME=/tmp/nobody-home git -c safe.directory=/tmp/repo -C /tmp/repo status'", "su nobody -s /bin/sh -c 'HOME=/tmp/nobody-home git -c safe.directory=/tmp/repo -C /tmp/repo status'", "Git's ownership safety check blocks a repository whose owner differs from the executing user; mark only the intended path safe or fix ownership.", ("Add the exact repository path to the executing user's safe.directory list.", "Re-run Git as that user.",), ("git", "permissions", "safe-directory")),
    Task("missing-config-path", "python:3.12.4", {"name": "python", "version": "3.12.4"}, "configuration", "FileNotFoundError", "A program fails because a relative configuration path is resolved from the wrong working directory.", "Starting a Python service from its project parent instead of its config directory.", "mkdir -p /tmp/app/config && printf 'port: 8080\n' > /tmp/app/config/settings.yml", "cd /tmp/app && python -c \"open('settings.yml').read()\"", ("cd /tmp && python -c \"open('/tmp/app/settings.yml').read()\"", "mkdir -p /tmp/app && touch /tmp/app/other.yml && cd /tmp/app && python -c \"open('settings.yml').read()\""), "cd /tmp/app && python -c \"open('config/settings.yml').read()\"", "cd /tmp/app && python -c \"open('config/settings.yml').read(); print('config ok')\"", "The relative path is interpreted from the process working directory; the file exists under config, not at the project root.", ("Use the project-relative config path.", "Start the service from a stable project directory.",), ("python", "paths", "configuration")),
    Task("rust-borrow-checker", "rust:1.78.0-bookworm", {"name": "rust", "version": "1.78.0"}, "build", "E0502", "Rust rejects a mutable method call while an immutable borrow from the same struct is still live.", "Compiling a small Rust service after adding a cache lookup.", "mkdir -p /tmp/app/src && printf '[package]\nname=\"app\"\nversion=\"0.1.0\"\nedition=\"2021\"\n' > /tmp/app/Cargo.toml && printf 'struct Store { value: String }\nimpl Store { fn refresh(&mut self) { self.value.push_str(\"x\"); } fn run(&mut self) { let current = &self.value; self.refresh(); println!(\"{}\", current); } }\nfn main() { Store { value: String::from(\"ok\") }.run(); }\n' > /tmp/app/src/main.rs", "cd /tmp/app && cargo check", ("cd /tmp/app && cargo check", "cd /tmp/app && cargo check --quiet"), "sed -i 's/let current = &self.value;/let current = self.value.clone();/' /tmp/app/src/main.rs && cd /tmp/app && cargo check", "cd /tmp/app && cargo check", "The reference held by current overlaps the mutable borrow needed by refresh; owning a clone ends the immutable borrow before mutation.", ("Clone the value when the mutable operation must follow the read.", "Run cargo check again.",), ("rust", "borrow-checker", "e0502", "cargo")),
    Task("docker-exec-format", "alpine:3.20", {"name": "docker", "version": "26"}, "platform", "exec format error", "A binary built for a different CPU architecture cannot be executed by the container.", "Running an arm64 ELF in an x86_64 build job.", "printf '\\177ELF\\002\\001\\001' > /tmp/tool && chmod +x /tmp/tool", "/tmp/tool", ("/tmp/tool", "exec /tmp/tool"), "printf '#!/bin/sh\necho tool ok\n' > /tmp/tool && chmod +x /tmp/tool", "/tmp/tool", "The kernel rejects the ELF header before permissions or shell logic matter; use a binary for the target architecture or a portable script.", ("Replace the foreign executable with a target-compatible script for this task.", "Make it executable.",), ("docker", "architecture", "exec-format")),
    Task("typescript-type-error", "node:18.20.4", {"name": "node", "version": "18.20.4"}, "build", "TS2322", "TypeScript rejects assigning a string to a variable declared as a number.", "Compiling a small TypeScript utility with strict checking enabled.", "mkdir -p /tmp/app && cd /tmp/app && npm install --no-audit --no-fund -q typescript@5.4.5 && printf '{\"compilerOptions\":{\"strict\":true}}\n' > tsconfig.json && printf 'const port: number = \"8080\"; console.log(port);\n' > index.ts", "cd /tmp/app && npx --no-install tsc --noEmit", ("cd /tmp/app && npx --no-install tsc --noEmit --skipLibCheck", "cd /tmp/app && npx --no-install tsc --noEmit --strict false"), "cd /tmp/app && sed -i 's/const port: number = \"8080\";/const port: number = 8080;/' index.ts && cd /tmp/app && npx --no-install tsc --noEmit", "cd /tmp/app && npx --no-install tsc --noEmit", "The declared type and initializer disagree; compiler suppression hides the defect instead of fixing the value.", ("Use a numeric literal for a number-typed port.", "Compile with strict checking still enabled.",), ("node", "typescript", "ts2322", "npm")),
    Task("python-port-in-use", "python:3.12.4", {"name": "python", "version": "3.12.4"}, "network", "OSError", "A second Python server cannot bind a TCP port already occupied by another process.", "Starting a development server on a port used by a health-check process.", "python -c \"import socket,time; s=socket.socket(); s.bind(('127.0.0.1', 8765)); s.listen(); time.sleep(30)\" & sleep 1", "python -c \"import socket; s=socket.socket(); s.bind(('127.0.0.1', 8765))\"", ("python -c \"import socket; s=socket.socket(); s.bind(('127.0.0.1', 8765))\"", "python -c \"import socket; s=socket.socket(); s.bind(('127.0.0.1', 8765))\""), "python -c \"import socket; s=socket.socket(); s.bind(('127.0.0.1', 8766)); print('bound')\"", "python -c \"import socket; s=socket.socket(); s.bind(('127.0.0.1', 8766)); print('bound')\"", "Only one listener can own the address and port; choose an available configured port or stop the process that owns it.", ("Identify the conflicting listener in the real host environment.", "Configure the service to use an available port.",), ("python", "network", "ports")),
    Task("python-missing-yaml", "python:3.12.4", {"name": "python", "version": "3.12.4"}, "dependency", "ModuleNotFoundError", "Python cannot import yaml because the import name belongs to the PyYAML distribution.", "Running a configuration loader in a clean Python image.", "", "python -c 'import yaml'", ("python -m pip install yaml==999.0.0", "python -m pip install PyYAML==999.0.0"), "python -m pip install -q PyYAML", "python -c 'import yaml; print(yaml.safe_load(\"port: 8080\")[\"port\"])'", "The import is named yaml but the package published on PyPI is PyYAML; installing a similarly named distribution does not provide the module.", ("Install PyYAML.", "Verify the yaml import and parse a real document.",), ("python", "yaml", "pypi")),
    Task("node-missing-module", "node:18.20.4", {"name": "node", "version": "18.20.4"}, "dependency", "MODULE_NOT_FOUND", "Node cannot load a dependency that is absent from node_modules.", "Starting a small script that requires the chalk package.", "mkdir -p /tmp/app && printf 'const chalk = require(\"chalk\"); console.log(chalk.green(\"ok\"));\n' > /tmp/app/index.js", "cd /tmp/app && node index.js", ("cd /tmp/app && npm install chalk@999.0.0 --no-audit --no-fund", "cd /tmp/app && npm install chalk@998.0.0 --no-audit --no-fund"), "cd /tmp/app && npm install chalk@4 --no-audit --no-fund", "cd /tmp/app && node index.js", "Node resolves CommonJS dependencies from the project's local node_modules; the dependency must be installed locally under the name used by require.", ("Install the exact package locally.", "Rerun the script from the project directory.",), ("node", "npm", "modules")),
    Task("node-npm-permission-cache", "node:18.20.4", {"name": "node", "version": "18.20.4"}, "permissions", "EACCES", "A Node build helper cannot write its npm cache directory when the directory is not writable.", "Preparing a package cache for a non-root Node build.", "mkdir -p /tmp/npm-cache && chmod 555 /tmp/npm-cache", "su nobody -s /bin/sh -c 'touch /tmp/npm-cache/probe'", ("su nobody -s /bin/sh -c 'touch /tmp/npm-cache/probe'", "chmod 555 /tmp/npm-cache && su nobody -s /bin/sh -c 'touch /tmp/npm-cache/probe'"), "chmod 755 /tmp/npm-cache && chown nobody:nogroup /tmp/npm-cache && su nobody -s /bin/sh -c 'touch /tmp/npm-cache/probe'", "su nobody -s /bin/sh -c 'test -f /tmp/npm-cache/probe && echo cache writable'", "The cache directory permissions deny the non-root build user write access; grant write access to the intended cache path.", ("Make the cache directory writable and owned by the build user.", "Retry the cache write as the build user.",), ("node", "npm", "permissions", "cache")),
    Task("go-missing-module", "golang:1.22.5", {"name": "go", "version": "1.22.5"}, "dependency", "no required module provides package", "Go refuses to build an import that is not declared in go.mod.", "Building a Go utility that uses uuid.New().", "mkdir -p /tmp/app && cd /tmp/app && go mod init example.test/app && printf 'package main\nimport \"github.com/google/uuid\"\nfunc main(){ _ = uuid.New() }\n' > main.go", "cd /tmp/app && go build ./...", ("cd /tmp/app && go get github.com/google/uuid@v0.0.0", "cd /tmp/app && go build ./..."), "cd /tmp/app && go get github.com/google/uuid@v1.6.0", "cd /tmp/app && go build ./...", "The import path is absent from the module graph; adding the matching module version makes the package available to the compiler.", ("Add the module that owns the imported package.", "Build again and confirm exit zero.",), ("go", "modules", "dependencies")),
    Task("cpp-missing-header", "gcc:13.2.0", {"name": "gcc", "version": "13.2.0"}, "build", "fatal error", "C++ compilation fails when a standard header is omitted.", "Compiling a program that uses std::vector.", "mkdir -p /tmp/app && printf '#include <iostream>\nint main(){ std::vector<int> v{1,2}; std::cout << v.size(); }\n' > /tmp/app/main.cpp", "g++ -std=c++17 /tmp/app/main.cpp -o /tmp/app/main", ("g++ -std=c++17 -fpermissive /tmp/app/main.cpp -o /tmp/app/main", "g++ -std=c++11 /tmp/app/main.cpp -o /tmp/app/main"), "sed -i '1i #include <vector>' /tmp/app/main.cpp && g++ -std=c++17 /tmp/app/main.cpp -o /tmp/app/main", "/tmp/app/main", "std::vector is declared by the <vector> header; compiler permissiveness and an older language mode do not supply a missing declaration.", ("Include the header that declares std::vector.", "Compile and run the resulting binary.",), ("cpp", "gcc", "headers")),
    Task("permissions-non-executable", "alpine:3.20", {"name": "sh", "version": "busybox"}, "permissions", "Permission denied", "A deployment script cannot run because its executable bit is missing.", "Running a script copied into an image with restrictive file permissions.", "printf '#!/bin/sh\necho deployed\n' > /tmp/deploy.sh && chmod 644 /tmp/deploy.sh", "/tmp/deploy.sh", ("chmod 600 /tmp/deploy.sh && /tmp/deploy.sh", "sh -c /tmp/deploy.sh"), "chmod 755 /tmp/deploy.sh", "/tmp/deploy.sh", "The file content is valid but the kernel requires execute permission for direct invocation; grant only the required executable bit.", ("Set the script mode to 755.", "Run the script directly.",), ("permissions", "shell", "deployment")),
    Task("python-dns-resolution", "python:3.12.4", {"name": "python", "version": "3.12.4"}, "network", "gaierror", "Python cannot resolve a hostname that is not present in DNS.", "Connecting a client using a misspelled service hostname.", "", "python -c \"import socket; socket.gethostbyname('dbb.invalid')\"", ("retry the same hostname", "connect to dbb.invalid:5432 without resolving it"), "python -c \"import socket; print(socket.gethostbyname('localhost'))\"", "python -c \"import socket; print(socket.gethostbyname('localhost'))\"", "The hostname is not resolvable; correct the configured service name or use a resolvable address in the target network.", ("Correct the hostname in configuration.", "Verify resolution before opening the connection.",), ("python", "dns", "network")),
    Task("java-release-mismatch", "maven:3.9.9-eclipse-temurin-17", {"name": "jvm", "version": "17"}, "build", "invalid target release", "Maven cannot compile source configured for a newer Java release than the installed JDK.", "Building a project configured with maven.compiler.release=21 on JDK 17.", "mkdir -p /tmp/app/src/main/java && printf '<project xmlns=\"http://maven.apache.org/POM/4.0.0\" xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" xsi:schemaLocation=\"http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd\"><modelVersion>4.0.0</modelVersion><groupId>x</groupId><artifactId>app</artifactId><version>1</version><properties><maven.compiler.release>21</maven.compiler.release></properties></project>' > /tmp/app/pom.xml && printf 'class Main { public static void main(String[] a) {} }\n' > /tmp/app/src/main/java/Main.java", "cd /tmp/app && mvn -q package", ("cd /tmp/app && mvn -q -DskipTests package", "cd /tmp/app && mvn -q -Dmaven.compiler.source=21 package"), "sed -i 's|<maven.compiler.release>21</|<maven.compiler.release>17</|' /tmp/app/pom.xml && cd /tmp/app && mvn -q package", "cd /tmp/app && mvn -q package", "The compiler release must not exceed the JDK's supported release; this build runs on Java 17.", ("Align the Maven release with the installed JDK.", "Run the package build again.",), ("java", "maven", "jdk", "release")),
    Task("gradle-daemon-cache", "gradle:8.7.0-jdk17", {"name": "jvm", "version": "17"}, "tooling", "Could not create service", "Gradle cannot create its cache when GRADLE_USER_HOME points at a read-only directory.", "Running Gradle with a cache directory mounted read-only.", "mkdir -p /tmp/gradle-cache && chown gradle:gradle /tmp/gradle-cache && chmod 555 /tmp/gradle-cache", "su gradle -s /bin/sh -c 'GRADLE_USER_HOME=/tmp/gradle-cache gradle --version'", ("su gradle -s /bin/sh -c 'GRADLE_USER_HOME=/tmp/gradle-cache gradle --offline --version'", "su gradle -s /bin/sh -c 'GRADLE_USER_HOME=/tmp/gradle-cache gradle --version'"), "chmod 755 /tmp/gradle-cache && su gradle -s /bin/sh -c 'GRADLE_USER_HOME=/tmp/gradle-cache gradle --version'", "su gradle -s /bin/sh -c 'GRADLE_USER_HOME=/tmp/gradle-cache gradle --version'", "Gradle needs to write metadata under GRADLE_USER_HOME; the configured cache must be writable by the build user.", ("Grant write access to the configured Gradle cache.", "Retry Gradle and inspect its version.",), ("gradle", "jvm", "cache")),
    Task("python-invalid-json", "python:3.12.4", {"name": "python", "version": "3.12.4"}, "data", "JSONDecodeError", "Python rejects a configuration file containing a trailing comma, which is not valid JSON.", "Loading a service configuration generated by a hand-edited template.", "printf '{\"port\": 8080,}\n' > /tmp/config.json", "python -c \"import json; json.load(open('/tmp/config.json'))\"", ("python -c \"import json; json.loads('{\\\"port\\\": 8080,}')\"", "python -c \"import json; json.load(open('/tmp/config.json'))\""), "printf '{\"port\": 8080}\n' > /tmp/config.json", "python -c \"import json; print(json.load(open('/tmp/config.json'))['port'])\"", "JSON does not permit a trailing comma; repair the document as JSON rather than parsing it with a more permissive language parser.", ("Remove the trailing comma.", "Load the repaired document with the JSON parser.",), ("python", "json", "configuration", "data")),
    Task("python-division-by-zero", "python:3.12.4", {"name": "python", "version": "3.12.4"}, "runtime", "ZeroDivisionError", "A calculation crashes when an empty input produces a zero denominator.", "Calculating an average for a possibly empty list of measurements.", "", "python -c \"values=[]; print(sum(values)/len(values))\"", ("python -c \"values=[]; print(sum(values)/len(values))\"", "python -c \"values=[]; print(sum(values)/0)\""), "python -c \"values=[]; average=sum(values)/len(values) if values else 0; print(average)\"", "python -c \"values=[]; average=sum(values)/len(values) if values else 0; print(average)\"", "The empty input has no denominator; handle the empty case explicitly instead of hiding the exception with an arbitrary divisor.", ("Return the documented empty-input value.", "Run the calculation with an empty fixture.",), ("python", "runtime", "arithmetic")),
    Task("node-env-port", "node:18.20.4", {"name": "node", "version": "18.20.4"}, "configuration", "ERR_INVALID_ARG_TYPE", "A Node server receives an undefined port because the required environment variable is absent.", "Starting a server from a process without its deployment environment.", "", "node -e \"if (!process.env.PORT) throw new TypeError('The \"port\" argument must be of type number. Received undefined')\"", ("node -e \"if (!process.env.PORT) throw new TypeError('The \\\"port\\\" argument must be of type number. Received undefined')\"", "PORT= node -e \"if (!process.env.PORT) throw new TypeError('The \\\"port\\\" argument must be of type number. Received undefined')\""), "PORT=8080 node -e \"if (!process.env.PORT) throw new TypeError('The port argument must be of type number. Received undefined')\"", "PORT=8080 node -e \"if (!process.env.PORT) throw new TypeError('The port argument must be of type number. Received undefined')\"", "listen requires a concrete numeric port; supply PORT through deployment configuration and verify the process starts.", ("Set PORT to the configured service port.", "Run the startup validation with the configured value.",), ("node", "configuration", "environment")),
    Task("cpp-undefined-reference", "gcc:13.2.0", {"name": "gcc", "version": "13.2.0"}, "build", "undefined reference", "The linker fails because a declared C++ function has no definition.", "Building a small executable after adding a header declaration.", "mkdir -p /tmp/app && printf 'int answer(); int main(){ return answer(); }\n' > /tmp/app/main.cpp", "g++ /tmp/app/main.cpp -o /tmp/app/main", ("g++ -Wl,--no-undefined /tmp/app/main.cpp -o /tmp/app/main", "g++ -fpermissive /tmp/app/main.cpp -o /tmp/app/main"), "printf 'int answer(){ return 42; }\n' >> /tmp/app/main.cpp && g++ /tmp/app/main.cpp -o /tmp/app/main", "/tmp/app/main; test $? -eq 42", "Compilation creates an object for the declaration but linking needs one definition of answer; provide it before linking.", ("Define the declared function.", "Link and run the executable to check its return value.",), ("cpp", "gcc", "linker")),
    Task("python-missing-requests", "python:3.12.4", {"name": "python", "version": "3.12.4"}, "dependency", "ModuleNotFoundError", "A clean Python runtime cannot import requests until the distribution is installed.", "Running an HTTP client script in a fresh container.", "", "python -c 'import requests; print(requests.__version__)'", ("python -m pip install request==999.0.0", "python -m pip install requests==999.0.0"), "python -m pip install -q requests", "python -c 'import requests; print(requests.__version__)'", "The standard library does not include requests; install the package named by the import.", ("Install requests in the active environment.", "Rerun the import as verification.",), ("python", "requests", "pypi")),
    Task("python-empty-environment-variable", "python:3.12.4", {"name": "python", "version": "3.12.4"}, "configuration", "KeyError", "A configuration lookup fails when a required environment variable is absent.", "Reading DATABASE_URL during application startup.", "", "python -c \"import os; print(os.environ['DATABASE_URL'])\"", ("python -c \"import os; print(os.environ['DATABASE_URL'])\"", "python -c \"import os; print(os.environ['DATABASE_URL'])\""), "DATABASE_URL=sqlite:///tmp/app.db python -c \"import os; print(os.environ['DATABASE_URL'])\"", "DATABASE_URL=sqlite:///tmp/app.db python -c \"import os; print(os.environ['DATABASE_URL'])\"", "The application requires DATABASE_URL; fail-fast is correct, but deployment must provide the variable before startup.", ("Set DATABASE_URL in the service environment.", "Run the startup check with the configured value.",), ("python", "environment", "configuration")),
    Task("go-type-mismatch", "golang:1.22.5", {"name": "go", "version": "1.22.5"}, "build", "cannot use", "Go rejects assigning a string literal to an integer variable.", "Compiling a small command-line configuration parser.", "mkdir -p /tmp/app && cd /tmp/app && go mod init example.test/types && printf 'package main\nfunc main(){ var port int = \"8080\"; _ = port }\n' > main.go", "cd /tmp/app && go build ./...", ("cd /tmp/app && go build ./...", "cd /tmp/app && go test ./..."), "sed -i 's/var port int = \"8080\"/var port int = 8080/' /tmp/app/main.go && cd /tmp/app && go build ./...", "cd /tmp/app && go build ./...", "The declared Go type is int, so the initializer must be an integer literal or be parsed before assignment.", ("Use an integer literal for this fixed configuration value.", "Build the corrected package.",), ("go", "types", "compiler")),
    Task("rust-type-mismatch", "rust:1.78.0-bookworm", {"name": "rust", "version": "1.78.0"}, "build", "E0308", "Rust rejects returning a string where a function promises an integer.", "Compiling a helper that returns a process port.", "mkdir -p /tmp/app/src && printf '[package]\nname=\"types\"\nversion=\"0.1.0\"\nedition=\"2021\"\n' > /tmp/app/Cargo.toml && printf 'fn port() -> u16 { \"8080\" }\nfn main(){ println!(\"{}\", port()); }\n' > /tmp/app/src/main.rs", "cd /tmp/app && cargo check", ("cd /tmp/app && cargo check", "cd /tmp/app && cargo test"), "sed -i 's/\"8080\"/8080/' /tmp/app/src/main.rs && cd /tmp/app && cargo check", "cd /tmp/app && cargo check", "The function return type is u16; parse the configuration string or use a numeric literal before returning it.", ("Use a numeric literal in this reproducible fixture.", "Run cargo check again.",), ("rust", "types", "e0308")),
    Task("python-syntax-error", "python:3.12.4", {"name": "python", "version": "3.12.4"}, "build", "SyntaxError", "Python refuses to run a file with an unterminated function call.", "Starting a utility after a hand-edited logging change.", "printf 'print(\"starting\"\n' > /tmp/app.py", "python /tmp/app.py", ("python -m py_compile /tmp/app.py", "python /tmp/app.py"), "printf 'print(\"starting\")\n' > /tmp/app.py", "python /tmp/app.py", "The source is syntactically incomplete; close the call before executing the program.", ("Close the unterminated call.", "Run the repaired script.",), ("python", "syntax", "runtime")),
    Task("python-indentation-error", "python:3.12.4", {"name": "python", "version": "3.12.4"}, "build", "IndentationError", "Python rejects a block whose statement indentation does not match its parent.", "Running a small conditional health check.", "printf 'if True:\nprint(\"ok\")\n' > /tmp/check.py", "python /tmp/check.py", ("python -m py_compile /tmp/check.py", "python /tmp/check.py"), "printf 'if True:\n    print(\"ok\")\n' > /tmp/check.py", "python /tmp/check.py", "Python blocks are delimited by indentation; indent the child statement consistently.", ("Indent the statement under the if block.", "Run the repaired check.",), ("python", "syntax", "indentation")),
    Task("python-permission-file", "python:3.12.4", {"name": "python", "version": "3.12.4"}, "permissions", "PermissionError", "Python cannot read a configuration file that is accessible only to another user.", "Loading a configuration file as a non-root service account.", "printf 'port=8080\n' > /tmp/secret.cfg && chmod 600 /tmp/secret.cfg", "su nobody -s /bin/sh -c 'cat /tmp/secret.cfg'", ("su nobody -s /bin/sh -c 'cat /tmp/secret.cfg'", "chmod 600 /tmp/secret.cfg && su nobody -s /bin/sh -c 'cat /tmp/secret.cfg'"), "chmod 644 /tmp/secret.cfg && su nobody -s /bin/sh -c 'cat /tmp/secret.cfg'", "su nobody -s /bin/sh -c 'cat /tmp/secret.cfg'", "The file mode grants access only to its owner; grant read access appropriate for the service account without making it writable.", ("Set the file mode to owner-write and world-read for this non-secret fixture.", "Read it again as the service account.",), ("python", "permissions", "files")),
    Task("cpp-multiple-definition", "gcc:13.2.0", {"name": "gcc", "version": "13.2.0"}, "build", "multiple definition", "The linker rejects the same non-inline function defined in two translation units.", "Linking two C++ source files after copying an implementation into both files.", "mkdir -p /tmp/app && printf 'int value(){return 1;}\n' > /tmp/app/a.cpp && printf 'int value(){return 1;} int main(){return value();}\n' > /tmp/app/b.cpp", "g++ /tmp/app/a.cpp /tmp/app/b.cpp -o /tmp/app/main", ("g++ /tmp/app/a.cpp /tmp/app/b.cpp -o /tmp/app/main", "g++ /tmp/app/a.cpp /tmp/app/b.cpp -o /tmp/app/main"), "printf 'int value(); int main(){return value();}\n' > /tmp/app/b.cpp && g++ /tmp/app/a.cpp /tmp/app/b.cpp -o /tmp/app/main", "/tmp/app/main; test $? -eq 1", "The linker sees two external definitions of value; keep one implementation and use a declaration in the caller.", ("Replace the duplicate implementation with a declaration.", "Link and run the corrected program.",), ("cpp", "gcc", "linker")),
    Task("shell-crlf-script", "alpine:3.20", {"name": "sh", "version": "busybox"}, "tooling", "not found", "BusyBox cannot find an interpreter when a script's shebang contains a carriage return.", "Running a shell script copied from a Windows checkout.", "printf '#!/bin/sh\r\necho ok\r\n' > /tmp/run.sh && chmod +x /tmp/run.sh", "/tmp/run.sh", ("/tmp/run.sh", "chmod +x /tmp/run.sh && /tmp/run.sh"), "sed -i 's/\r$//' /tmp/run.sh && /tmp/run.sh", "/tmp/run.sh", "The CRLF line ending becomes part of the shebang path; convert the script to LF before direct execution.", ("Remove carriage returns from the script.", "Run it directly with its corrected shebang.",), ("shell", "crlf", "portability")),
    Task("node-json-parse", "node:18.20.4", {"name": "node", "version": "18.20.4"}, "data", "SyntaxError", "Node rejects malformed JSON when a configuration value has a trailing comma.", "Loading an application configuration file with JSON.parse.", "printf '{\"port\":8080,}\n' > /tmp/config.json", "node -e \"JSON.parse(require('fs').readFileSync('/tmp/config.json','utf8'))\"", ("node -e \"JSON.parse(require('fs').readFileSync('/tmp/config.json','utf8'))\"", "node -e \"JSON.parse('{\\\"port\\\":8080,}')\""), "printf '{\"port\":8080}\n' > /tmp/config.json", "node -e \"console.log(JSON.parse(require('fs').readFileSync('/tmp/config.json','utf8')).port)\"", "JSON syntax does not allow a trailing comma; repair the document before parsing it.", ("Remove the trailing comma.", "Parse the corrected JSON as the verification step.",), ("node", "json", "configuration")),
    Task("go-undefined-symbol", "golang:1.22.5", {"name": "go", "version": "1.22.5"}, "build", "undefined", "Go compilation fails when code calls a function that is not declared in the package.", "Building a command after renaming a helper but not its call site.", "mkdir -p /tmp/app && cd /tmp/app && go mod init example.test/symbol && printf 'package main\nfunc main(){ missingHelper() }\n' > main.go", "cd /tmp/app && go build ./...", ("cd /tmp/app && go test ./...", "cd /tmp/app && go vet ./..."), "sed -i 's/missingHelper()/helper()/' /tmp/app/main.go && sed -i '2i func helper() {}' /tmp/app/main.go && cd /tmp/app && go build ./...", "cd /tmp/app && go build ./...", "The call refers to no declared function; update the call and provide the helper implementation in the package.", ("Define the helper and use its current name.", "Build the corrected package.",), ("go", "compiler", "symbols")),
    Task("python-unicode-decode", "python:3.12.4", {"name": "python", "version": "3.12.4"}, "data", "UnicodeDecodeError", "Python cannot decode UTF-8 data with an ASCII codec.", "Reading a UTF-8 configuration file using an explicitly wrong encoding.", "printf '\303\251\n' > /tmp/name.txt", "python -c \"open('/tmp/name.txt', encoding='ascii').read()\"", ("python -c \"open('/tmp/name.txt', encoding='ascii').read()\"", "python -c \"open('/tmp/name.txt', encoding='ascii').read()\""), "python -c \"print(open('/tmp/name.txt', encoding='utf-8').read().strip())\"", "python -c \"print(open('/tmp/name.txt', encoding='utf-8').read().strip())\"", "The file contains UTF-8 bytes; decode it with UTF-8 instead of silently dropping or misinterpreting bytes.", ("Use the file's UTF-8 encoding.", "Read it again and verify the decoded text.",), ("python", "unicode", "encoding")),
    Task("python-numpy-cp312-wheel", "python:3.12.4", {"name": "python", "version": "3.12.4"}, "dependency", "No matching distribution found", "Pip cannot satisfy an old NumPy pin from binary wheels on CPython 3.12.", "Installing a requirements file that pins NumPy 1.24 on a Python 3.12 image.", "", "python -m pip install --only-binary=:all: numpy==1.24.4", ("python -m pip install --only-binary=:all: numpy==1.24.4", "python -m pip install --only-binary=:all: numpy==1.24.4 --no-cache-dir"), "python -m pip install -q --only-binary=:all: numpy==1.26.4", "python -c 'import numpy; print(numpy.__version__)'", "NumPy 1.24.4 does not publish a CPython 3.12 wheel, while NumPy 1.26.4 does; changing only pip flags cannot create a missing wheel.", ("Move the pin to the first compatible NumPy release.", "Import NumPy and print its installed version.",), ("python", "numpy", "wheels", "python3.12")),
    Task("npm-lockfile-drift", "node:18.20.4", {"name": "node", "version": "18.20.4"}, "dependency", "npm ci", "npm ci refuses to install when package.json and package-lock.json describe different dependency versions.", "Replaying a committed lockfile after changing a dependency range without regenerating it.", "mkdir -p /tmp/app && cd /tmp/app && printf '{\"private\":true,\"dependencies\":{\"lodash\":\"4.17.21\"}}\n' > package.json && npm install --package-lock-only --ignore-scripts --no-audit --no-fund && sed -i 's/4.17.21/4.17.20/' package.json", "cd /tmp/app && npm ci --ignore-scripts --no-audit --no-fund", ("cd /tmp/app && npm ci --ignore-scripts --no-audit --no-fund", "cd /tmp/app && npm ci --ignore-scripts --no-audit --no-fund"), "cd /tmp/app && npm install --package-lock-only --ignore-scripts --no-audit --no-fund && npm ci --ignore-scripts --no-audit --no-fund", "cd /tmp/app && node -e \"console.log(require('lodash').VERSION)\"", "npm ci is intentionally reproducible and therefore rejects package metadata that no longer matches the committed lockfile; regenerate the lockfile before using ci.", ("Regenerate package-lock.json from the current package.json.", "Run npm ci again and verify the installed version.",), ("node", "npm", "lockfile")),
    Task("rust-use-after-move", "rust:1.78.0-bookworm", {"name": "rust", "version": "1.78.0"}, "build", "E0382", "Rust rejects using a String after it has been moved into another variable.", "Compiling code that keeps a label after passing ownership to a worker function.", "mkdir -p /tmp/app/src && printf '[package]\nname=\"movecheck\"\nversion=\"0.1.0\"\nedition=\"2021\"\n' > /tmp/app/Cargo.toml && printf 'fn consume(s:String){println!(\"{}\",s)}\nfn main(){let label=String::from(\"worker\"); consume(label); println!(\"{}\",label);}\n' > /tmp/app/src/main.rs", "cd /tmp/app && cargo check", ("cd /tmp/app && cargo check", "cd /tmp/app && cargo test"), "sed -i 's/consume(label);/consume(label.clone());/' /tmp/app/src/main.rs && cd /tmp/app && cargo check", "cd /tmp/app && cargo check", "Passing a String by value transfers ownership; clone it when both the callee and caller must use the value.", ("Clone the label for the consuming call.", "Run cargo check after the ownership fix.",), ("rust", "ownership", "e0382")),
    Task("go-missing-package", "golang:1.22.5", {"name": "go", "version": "1.22.5"}, "dependency", "no required module provides package", "Go cannot resolve an imported package until its module is added to go.mod.", "Building a utility that imports a UUID package in a new module.", "mkdir -p /tmp/app && cd /tmp/app && go mod init example.test/uuid && printf 'package main\nimport \"github.com/google/uuid\"\nfunc main(){println(uuid.Nil.String())}\n' > main.go", "cd /tmp/app && go build ./...", ("cd /tmp/app && go get github.com/google/uuid@v0.0.0", "cd /tmp/app && go build ./..."), "cd /tmp/app && go get github.com/google/uuid@v1.6.0 && go build ./...", "cd /tmp/app && go build ./...", "The imported package is outside the module graph; add its real module at a compatible version before building.", ("Add the module that owns the import.", "Build the module again.",), ("go", "modules", "imports")),
)


# A trail is worth publishing only when an agent that hits the error would plausibly search for it
# and the fix does not depend on the agent's own code. Errors a capable agent solves at a glance are
# never searched, and errors in someone's source code have fixes that do not transfer. Tasks listed
# here stay in the catalog (they are reproducible and useful as tests) but are not published.
POLICY_EXCLUDED = {
    # The fix is a change to the user's own source code.
    "rust-borrow-checker": "code-level: the fix depends on the user's code",
    "rust-use-after-move": "code-level: the fix depends on the user's code",
    "rust-type-mismatch": "code-level: the fix depends on the user's code",
    "typescript-type-error": "code-level: the fix depends on the user's code",
    "go-type-mismatch": "code-level: the fix depends on the user's code",
    "go-undefined-symbol": "code-level: the fix depends on the user's code",
    "cpp-missing-header": "code-level: the fix depends on the user's code",
    "cpp-undefined-reference": "code-level: the fix depends on the user's code",
    "cpp-multiple-definition": "code-level: the fix depends on the user's code",
    "python-syntax-error": "code-level: the fix depends on the user's code",
    "python-indentation-error": "code-level: the fix depends on the user's code",
    "python-division-by-zero": "code-level: the fix depends on the user's code",
    "python-empty-environment-variable": "code-level: the fix depends on the user's code",
    "node-env-port": "code-level: the fix depends on the user's code",
    # The task does not reproduce what its trail would claim.
    "docker-exec-format": "not reproduced: the container shell reports 'not found', not the kernel's exec format error",
    # Obvious at a glance: an agent solves it without searching, so nobody would look it up.
    "python-invalid-json": "obvious: an agent fixes it at a glance",
    "node-json-parse": "obvious: an agent fixes it at a glance",
    "python-unicode-decode": "obvious: an agent fixes it at a glance",
    "missing-config-path": "obvious: an agent fixes it at a glance",
    "python-dns-resolution": "obvious: an agent fixes it at a glance",
    "python-permission-file": "obvious: an agent fixes it at a glance",
    "permissions-non-executable": "obvious: an agent fixes it at a glance",
    "python-port-in-use": "obvious: an agent fixes it at a glance",
    "node-missing-module": "obvious: an agent fixes it at a glance",
    "python-missing-requests": "obvious: an agent fixes it at a glance",
    "go-missing-module": "obvious: an agent fixes it at a glance",
    "go-missing-package": "obvious: an agent fixes it at a glance",
}


def publishable() -> tuple[Task, ...]:
    return tuple(t for t in TASKS if t.task_id not in POLICY_EXCLUDED)


# For the few tasks whose captured output does not carry the message people actually search for on
# one line, the line to use. It is only used when the container really printed it.
MESSAGE_OVERRIDES = {
    "node-openssl-md4": "Error: error:0308010C:digital envelope routines::unsupported",
    "git-safe-directory": "fatal: detected dubious ownership in repository",
}
