from .probes import from_probe

PY312 = {"name": "python", "version": "3.12"}
PY311 = {"name": "python", "version": "3.11"}

TASKS = (
    from_probe(
        "py-numpy2-float_", category="api_contract", error_type="AttributeError", runtime=PY312, message="`np.float_` was removed",
        summary="NumPy 2.0 removed the np.float_ alias, so code written for NumPy 1.x that calls np.float_ fails with an AttributeError after the upgrade.",
        context="Running a script that was written against NumPy 1.x after pip installed NumPy 2.0.",
        extra_setup="mkdir -p /w && printf 'import numpy as np\\nprint(np.float_(1))\\n' > /w/app.py", failing="cd /w && python app.py 2>&1",
        failed_approaches=('python -c "import numpy as np; np.float"', 'python -c "import numpy as np; print(np.float_)"'),
        fix="cd /w && sed -i 's/np.float_/np.float64/g' app.py", verify="cd /w && python app.py",
        root_cause="NumPy 2.0 removed the aliases that duplicated a name with a trailing underscore or a Python type (np.float_, np.NaN, np.Inf and others). np.float64 is the same type under its real name.",
        steps=("Replace np.float_ with np.float64 wherever it is used.", "If a dependency is the one calling np.float_, upgrade it to a release that supports NumPy 2, or pin numpy<2 until it does."),
        tags=("python", "numpy", "numpy2", "removed-alias"),
    ),
    from_probe(
        "py-numpy2-nan", category="api_contract", error_type="AttributeError", runtime=PY312, message="`np.NaN` was removed",
        summary="NumPy 2.0 removed np.NaN, np.NAN and np.Inf, so code that spelled the not-a-number constant that way fails after the upgrade.",
        context="Running data-cleaning code written for NumPy 1.x on NumPy 2.0.",
        extra_setup="mkdir -p /w && printf 'import numpy as np\\nprint(np.NaN)\\n' > /w/app.py", failing="cd /w && python app.py 2>&1",
        failed_approaches=('python -c "import numpy as np; np.NAN"', 'python -c "import numpy as np; np.Nan"'),
        fix="cd /w && sed -i 's/np.NaN/np.nan/g' app.py", verify="cd /w && python app.py",
        root_cause="NumPy 2.0 kept one lowercase spelling for each constant: np.nan and np.inf. The capitalised aliases were removed.",
        steps=("Use np.nan and np.inf.", "Search the whole project for NaN and Inf spelled with capitals, including notebooks and dependencies you vendor."),
        tags=("python", "numpy", "numpy2", "removed-alias"),
    ),
    from_probe(
        "py-jinja31-markup", category="api_contract", error_type="ImportError", runtime=PY312,
        summary="Jinja2 3.1 no longer re-exports Markup and escape, so an import from jinja2 that worked on 3.0 fails with ImportError.",
        context="Running an older Flask or Jinja2 extension after Jinja2 was upgraded to 3.1.",
        extra_setup="mkdir -p /w && printf 'from jinja2 import Markup\\nprint(Markup(\"<b>x</b>\"))\\n' > /w/app.py", failing="cd /w && python app.py 2>&1",
        failed_approaches=('python -c "from jinja2 import escape"', 'python -c "import jinja2; jinja2.Markup"'),
        fix="cd /w && sed -i 's/from jinja2 import Markup/from markupsafe import Markup/' app.py", verify="cd /w && python app.py",
        root_cause="Jinja2 3.1 removed the names it had re-exported from MarkupSafe (Markup, escape). They have always lived in the markupsafe package, which Jinja2 depends on.",
        steps=("Import Markup and escape from markupsafe.", "If a third-party package does the old import, upgrade it; pinning Jinja2<3.1 is only a stopgap."),
        tags=("python", "jinja2", "markupsafe", "removed-reexport"),
    ),
    from_probe(
        "py-django4-force-text", category="api_contract", error_type="ImportError", runtime=PY312,
        summary="Django 4.0 removed force_text and smart_text from django.utils.encoding, so imports written for Django 3.x fail with ImportError.",
        context="Upgrading a project, or one of its third-party apps, from Django 3.2 to 4.x.",
        extra_setup="mkdir -p /w && printf 'from django.utils.encoding import force_text\\nprint(force_text(b\"ok\"))\\n' > /w/app.py", failing="cd /w && python app.py 2>&1",
        failed_approaches=('python -c "from django.utils.encoding import force_unicode"', 'python -c "from django.utils import encoding; print(encoding.force_text)"'),
        fix="cd /w && sed -i 's/force_text/force_str/g' app.py", verify="cd /w && python app.py",
        root_cause="Django 3.0 deprecated force_text, smart_text and the other *_text helpers in favour of force_str and smart_str, and Django 4.0 removed them.",
        steps=("Replace force_text with force_str and smart_text with smart_str.", "If the call comes from a third-party app, upgrade that app to a release that supports Django 4."),
        tags=("python", "django", "django4", "removed-api"),
    ),
    from_probe(
        "py-werkzeug3-url-quote", category="dependency", error_type="ImportError", runtime=PY312,
        summary="Flask 2.2.2 and older import url_quote from werkzeug.urls, which Werkzeug 3.0 removed, so importing flask fails when pip resolves a newer Werkzeug.",
        context="Installing or running an application that pins an old Flask but not Werkzeug.",
        failed_approaches=('python -c "from werkzeug.urls import url_quote"', 'python -c "from werkzeug.urls import url_encode"'),
        fix="pip install -q -U flask", verify='python -c "import flask; print(flask.__version__)"',
        root_cause="Flask 2.2.2 and earlier did not cap Werkzeug, and called url_quote, which Werkzeug 3.0 removed. Newer Flask releases no longer use it.",
        steps=("Upgrade Flask to 2.3 or later.", "If you cannot upgrade, pin werkzeug<3 in the same requirements file as Flask."),
        tags=("python", "flask", "werkzeug", "version-conflict"),
    ),
    from_probe(
        "py-httpx028-proxies", category="dependency", error_type="TypeError", runtime=PY312,
        summary="httpx 0.28 removed the proxies argument, so OpenAI client releases that still pass it to httpx.Client fail on construction with a TypeError.",
        context="Creating an OpenAI client after pip resolved the newest httpx next to an older openai package.",
        failed_approaches=('python -c "import httpx; httpx.Client(proxies=\'http://localhost:3128\')"', 'python -c "import httpx; httpx.Client(proxies={})"'),
        fix="pip install -q -U openai", verify='python -c "import openai; openai.OpenAI(api_key=\'x\'); print(\'ok\')"',
        root_cause="httpx 0.28 dropped the deprecated proxies argument in favour of proxy and mounts. openai releases before 1.56 and several other SDKs still passed proxies, and their requirements did not cap httpx.",
        steps=("Upgrade the SDK that builds the client (openai 1.56 or later stopped passing proxies).", "Alternatively pin httpx<0.28 until every package that calls it is upgraded."),
        tags=("python", "httpx", "openai", "version-conflict"),
    ),
    from_probe(
        "py-pyyaml541-cython3", category="dependency", error_type="AttributeError", runtime=PY311,
        summary="Installing PyYAML 5.4.1 from source fails at build time with an AttributeError about cython_sources, because its build now pulls Cython 3.",
        context="Running pip install on a requirements file that pins pyyaml==5.4.1, for example in an old Docker image or CI job.",
        failing="pip install pyyaml==5.4.1 2>&1",
        failed_approaches=('pip install -q setuptools wheel && pip install pyyaml==5.4.1 2>&1', 'pip install -q cython==0.29.36 && pip install pyyaml==5.4.1 2>&1'),
        fix="pip install -q pyyaml", verify='python -c "import yaml; print(yaml.__version__)"',
        root_cause="PyYAML 5.4.1 has no wheel for this Python, so pip builds it in an isolated environment that installs the newest Cython. Cython 3 broke the old setup, and a Cython installed in your own environment is not seen by that isolated build.",
        steps=("Install a PyYAML release that publishes wheels for your Python (6.0 or later).", "If you must stay on 5.4.1, install Cython<3 and then run pip install pyyaml==5.4.1 --no-build-isolation, so that the build uses the Cython you installed."),
        tags=("python", "pyyaml", "cython", "build-isolation"),
    ),
    from_probe(
        "py-pyyaml6-load-loader", category="api_contract", error_type="TypeError", runtime=PY312,
        summary="PyYAML 6.0 made the Loader argument of yaml.load required, so calls that relied on the default fail with a TypeError.",
        context="Running a script written for PyYAML 5 after upgrading to PyYAML 6.",
        extra_setup="mkdir -p /w && printf 'import yaml\\nprint(yaml.load(\"a: 1\"))\\n' > /w/app.py", failing="cd /w && python app.py 2>&1",
        failed_approaches=('python -c "import yaml; yaml.load(\'a: 1\', Loader=None)"', 'pip install -q "pyyaml<6" 2>&1'),
        fix="cd /w && sed -i 's/yaml.load(/yaml.safe_load(/' app.py", verify="cd /w && python app.py",
        root_cause="PyYAML 5.1 deprecated calling yaml.load without a Loader, because the default loader could run arbitrary code, and 6.0 made the argument mandatory.",
        steps=("Use yaml.safe_load for untrusted or plain data.", "Pass Loader=yaml.SafeLoader (or FullLoader when you really need Python tags) if you must keep calling yaml.load."),
        tags=("python", "pyyaml", "removed-default"),
    ),
    from_probe(
        "py-setuptools75-test-command", category="tooling", error_type="invalid command", runtime=PY312,
        summary="Running python setup.py test fails with invalid command 'test' on setuptools 72 and later, which removed the test command.",
        context="A project with a legacy setup.py whose CI still calls python setup.py test.",
        failed_approaches=("cd /w && python setup.py pytest 2>&1", "cd /w && python setup.py nosetests 2>&1"),
        fix="pip install -q pytest && cd /w && printf 'def test_ok():\\n    assert True\\n' > test_ok.py", verify="cd /w && pytest -q",
        root_cause="setuptools deprecated the test command in 41 and removed it in 72. A setup.py is a build script, not a test runner, and calling it directly is deprecated.",
        steps=("Run the tests with pytest (or your runner) directly.", "Move test dependencies to an extra or a requirements file and update the CI job."),
        tags=("python", "setuptools", "setup-py", "removed-command"),
    ),
    from_probe(
        "py-sqlalchemy2-engine-execute", category="api_contract", error_type="AttributeError", runtime=PY312,
        summary="SQLAlchemy 2.0 removed Engine.execute, so code that ran SQL straight on an engine fails with an AttributeError.",
        context="Upgrading an application from SQLAlchemy 1.4 to 2.0.",
        extra_setup="mkdir -p /w && printf 'from sqlalchemy import create_engine\\ne = create_engine(\"sqlite://\")\\nprint(e.execute(\"select 1\").scalar())\\n' > /w/app.py", failing="cd /w && python app.py 2>&1",
        failed_approaches=("python -c \"from sqlalchemy import create_engine; e = create_engine('sqlite://'); e.connect().execute('select 1')\"", "python -c \"from sqlalchemy import create_engine; create_engine('sqlite://', future=False)\""),
        fix="cd /w && printf 'from sqlalchemy import create_engine, text\\ne = create_engine(\"sqlite://\")\\nwith e.connect() as c:\\n    print(c.execute(text(\"select 1\")).scalar())\\n' > app.py",
        verify="cd /w && python app.py",
        root_cause="SQLAlchemy 2.0 removed implicit execution on the engine and requires a Connection, and it no longer accepts a plain string as SQL: text() wraps it.",
        steps=("Open a connection with engine.connect() (or engine.begin() for a transaction).", "Wrap raw SQL in sqlalchemy.text().", "Commit explicitly when you write: connections no longer autocommit."),
        tags=("python", "sqlalchemy", "sqlalchemy2", "removed-api"),
    ),
    from_probe(
        "py-sqlalchemy2-postgres-dialect", category="configuration", error_type="NoSuchModuleError", runtime=PY312, message="Can't load plugin: sqlalchemy.dialects:postgres",
        summary="SQLAlchemy 1.4 removed the postgres:// URL scheme, so a DATABASE_URL that starts with postgres:// (as some hosting platforms provide) fails with NoSuchModuleError.",
        context="Pointing SQLAlchemy at a connection string handed out by a hosting platform.",
        failed_approaches=("python -c \"from sqlalchemy import create_engine; create_engine('postgresql+psycopg2://u:p@h/db')\"", "python -c \"from sqlalchemy import create_engine; create_engine('postgres+psycopg2://u:p@h/db')\""),
        fix="pip install -q psycopg2-binary", verify="python -c \"from sqlalchemy import create_engine; create_engine('postgresql://u:p@h/db'); print('ok')\"",
        root_cause="SQLAlchemy deprecated the postgres dialect name in 1.3 and removed it in 1.4; the dialect is postgresql. The scheme must be rewritten, and a driver such as psycopg2 must be installed for the engine to load it.",
        steps=("Replace the postgres:// prefix with postgresql://, for example with url.replace('postgres://', 'postgresql://', 1).", "Install a driver (psycopg2-binary or psycopg) in the same environment."),
        tags=("python", "sqlalchemy", "postgres", "connection-string"),
    ),
    from_probe(
        "py-torch26-weights-only", category="api_contract", error_type="UnpicklingError", runtime=PY312, memory="4g", message="Weights only load failed",
        summary="PyTorch 2.6 changed torch.load to weights_only=True by default, so loading a checkpoint that contains arbitrary Python objects fails with an UnpicklingError.",
        context="Loading a checkpoint saved with an older PyTorch, or one that stores a custom class, after upgrading to PyTorch 2.6.",
        failed_approaches=("python -c \"import torch\nclass A: pass\ntorch.save(A(), '/tmp/a.pt')\ntorch.load('/tmp/a.pt', weights_only=True)\" 2>&1", "python -c \"import torch\nclass A: pass\ntorch.save(A(), '/tmp/a.pt')\ntorch.load('/tmp/a.pt', mmap=True)\" 2>&1"),
        fix="python -c \"import torch\nclass A: pass\ntorch.save(A(), '/tmp/a.pt')\nprint(type(torch.load('/tmp/a.pt', weights_only=False)).__name__)\"",
        verify="python -c \"import torch; print(torch.__version__)\"",
        root_cause="Unpickling can run arbitrary code, so PyTorch 2.6 made torch.load refuse anything but tensors and a short allowlist unless you opt out. A checkpoint that pickles another class needs either that class allowlisted or weights_only=False.",
        steps=("Only if you trust the file: pass weights_only=False.", "Better: save a state_dict and load it, or allowlist the classes with torch.serialization.add_safe_globals([...]).", "Never use weights_only=False on a checkpoint from an untrusted source."),
        tags=("python", "pytorch", "torch.load", "pickle"),
    ),
    from_probe(
        "py-uv-no-venv", category="tooling", error_type="uv pip install", runtime=PY312,
        summary="uv pip install refuses to run outside a virtual environment, unlike pip, and tells you to create one or pass --system.",
        context="Replacing pip with uv in a Dockerfile or a CI script that has no virtual environment.",
        failed_approaches=("uv add six 2>&1", "uv pip install six --python python3.99 2>&1"),
        fix="uv venv && uv pip install six", verify='.venv/bin/python -c "import six; print(six.__version__)"',
        root_cause="uv pip never installs into a system interpreter by default; it looks for an active or .venv environment and stops when it finds none. That is intentional, to avoid modifying the system Python.",
        steps=("Create an environment first: uv venv, then uv pip install.", "In a throwaway container where installing into the system Python is what you want, pass --system (or set UV_SYSTEM_PYTHON=1).", "For a project with a pyproject.toml, use uv sync or uv add instead of uv pip."),
        tags=("python", "uv", "virtualenv", "docker"),
    ),
)

TASKS += (
    from_probe(
        "py-scipy114-simps", category="api_contract", error_type="ImportError", runtime=PY312,
        summary="SciPy 1.14 removed scipy.integrate.simps, trapz and cumtrapz, so an import written for older SciPy fails with ImportError.",
        context="Running numerical code after upgrading SciPy to 1.14.",
        extra_setup="mkdir -p /w && printf 'from scipy.integrate import simps\\nprint(simps([1, 2, 3]))\\n' > /w/app.py", failing="cd /w && python app.py 2>&1",
        failed_approaches=('python -c "import scipy.integrate as i; i.simps"', 'python -c "from scipy.integrate import simpson, simps"'),
        fix="cd /w && sed -i 's/simps/simpson/g' app.py", verify="cd /w && python app.py",
        root_cause="The simps, trapz and cumtrapz names were deprecated in SciPy 1.12 in favour of simpson, trapezoid and cumulative_trapezoid, and 1.14 removed them.",
        steps=("Use scipy.integrate.simpson (and trapezoid, cumulative_trapezoid).", "Note simpson's keyword is x= and dx=, and its default behaviour for an even number of points differs; check the docs.", "If a dependency imports the old name, upgrade it or pin scipy<1.14."),
        tags=("python", "scipy", "scipy1.14", "removed-api"),
    ),
    from_probe(
        "py-playwright-browsers-missing", category="tooling", error_type="Executable doesn't exist", runtime=PY312, memory="3g",
        summary="Playwright fails to launch Chromium with Executable doesn't exist because pip installs the library but not the browsers; they are downloaded by a separate command.",
        context="Running a Playwright script in a fresh container, CI job or virtual environment.",
        failed_approaches=("""PLAYWRIGHT_BROWSERS_PATH=/tmp/pw python -c "from playwright.sync_api import sync_playwright\nwith sync_playwright() as p:\n    p.chromium.launch()" 2>&1""", """python -c "from playwright.sync_api import sync_playwright\nwith sync_playwright() as p:\n    p.chromium.launch(executable_path='/usr/bin/chromium')" 2>&1"""),
        fix="python -m playwright install --with-deps chromium >/dev/null 2>&1",
        verify="""python -c "from playwright.sync_api import sync_playwright\nwith sync_playwright() as p:\n    b = p.chromium.launch(); print(b.version); b.close()" """,
        root_cause="The playwright package contains the driver and the API. The browser builds it was tested with are fetched by playwright install into a cache, and a slim image also lacks the system libraries Chromium needs, which --with-deps installs.",
        steps=("Run python -m playwright install chromium (add --with-deps in a Debian-based container to install the system libraries).", "In Docker, use the mcr.microsoft.com/playwright/python image, which has them already.", "Cache ~/.cache/ms-playwright in CI to avoid downloading on every run."),
        tags=("python", "playwright", "browsers", "docker"),
    ),
)

TASKS += (
    from_probe(
        "py-pydantic2-root-validator-skip", category="api_contract", error_type="PydanticUserError", runtime=PY312,
        summary="Pydantic 2 refuses a @root_validator without pre=True unless it also says skip_on_failure=True; code migrated from Pydantic 1 fails at class definition.",
        context="Importing a model module written for Pydantic 1 after upgrading to Pydantic 2.",
        extra_setup=r"""mkdir -p /w && printf 'from pydantic import BaseModel, root_validator\n\nclass M(BaseModel):\n    a: int\n\n    @root_validator\n    def check(cls, values):\n        return values\n' > /w/app.py""",
        failing="cd /w && python app.py 2>&1",
        failed_approaches=("""cd /w && sed -i 's/@root_validator/@root_validator(pre=False)/' app.py && python app.py 2>&1""", """cd /w && sed -i 's/def check(cls, values)/def check(values)/' app.py && python app.py 2>&1"""),
        fix=r"""cd /w && printf 'from pydantic import BaseModel, model_validator\n\nclass M(BaseModel):\n    a: int\n\n    @model_validator(mode="after")\n    def check(self):\n        return self\n\nprint(M(a=1))\n' > app.py""",
        verify="cd /w && python app.py",
        root_cause="Pydantic 2 deprecated @root_validator in favour of @model_validator. A post-validation root validator would otherwise run on data that already failed, so it must opt in with skip_on_failure=True; model_validator(mode='after') receives the validated model instead.",
        steps=("Use @model_validator(mode='after') (the method takes self) or mode='before' (a classmethod taking the raw data).", "To keep the old decorator for now: @root_validator(skip_on_failure=True)."),
        tags=("python", "pydantic", "pydantic2", "validator"), message="you MUST specify `skip_on_failure=True`",
    ),
    from_probe(
        "py-numpy2-product-removed", category="api_contract", error_type="AttributeError", runtime=PY312,
        summary="NumPy 2.0 removed np.product, np.cumproduct, np.alltrue and np.sometrue, so code that used those spellings fails with an AttributeError.",
        context="Running numerical code written for NumPy 1.x on NumPy 2.0.",
        extra_setup=r"""mkdir -p /w && printf 'import numpy as np\nprint(np.product([1, 2, 3]))\n' > /w/app.py""", failing="cd /w && python app.py 2>&1",
        failed_approaches=("""python -c "import numpy as np; np.alltrue([True])" """, """python -c "from numpy import product" """),
        fix="cd /w && sed -i 's/np.product/np.prod/g' app.py", verify="cd /w && python app.py",
        root_cause="NumPy 2.0 cleaned up its namespace: np.product became np.prod, np.cumproduct np.cumprod, np.alltrue np.all and np.sometrue np.any. The old names had been deprecated since 1.25.",
        steps=("Use np.prod, np.cumprod, np.all and np.any.", "Run ruff's NPY201 rule over the project: it finds these removed names."),
        tags=("python", "numpy", "numpy2", "removed-alias"), message="has no attribute 'product'",
    ),
    from_probe(
        "py-numpy2-cast-removed", category="api_contract", error_type="AttributeError", runtime=PY312,
        summary="NumPy 2.0 removed np.cast, the table of conversion functions, so code that called np.cast[dtype](x) fails with an AttributeError that names the replacement.",
        context="Running code written for NumPy 1.x on NumPy 2.0.",
        extra_setup=r"""mkdir -p /w && printf 'import numpy as np\nprint(np.cast[np.float32]([1, 2]))\n' > /w/app.py""", failing="cd /w && python app.py 2>&1",
        failed_approaches=("""python -c "import numpy as np; np.cast" """, """python -c "from numpy import cast" """),
        fix=r"""cd /w && printf 'import numpy as np\nprint(np.asarray([1, 2], dtype=np.float32))\n' > app.py""", verify="cd /w && python app.py",
        root_cause="np.cast mapped dtypes to converters and was deprecated in NumPy 1.25. NumPy 2.0 removed it; np.asarray(arr, dtype=dtype) does the same job.",
        steps=("Replace np.cast[dtype](x) with np.asarray(x, dtype=dtype), or x.astype(dtype).", "Run ruff's NPY201 rule over the project to find the rest."),
        tags=("python", "numpy", "numpy2", "removed-api"), message="`np.cast` was removed",
    ),
    from_probe(
        "py-pandas2-iteritems", category="api_contract", error_type="AttributeError", runtime=PY312,
        summary="pandas 2.0 removed DataFrame.iteritems and Series.iteritems, so loops written for pandas 1.x fail with an AttributeError; items() is the replacement.",
        context="Upgrading a data pipeline from pandas 1.x to 2.x.",
        extra_setup=r"""mkdir -p /w && printf 'import pandas as pd\ndf = pd.DataFrame({"a": [1, 2]})\nfor name, column in df.iteritems():\n    print(name, list(column))\n' > /w/app.py""", failing="cd /w && python app.py 2>&1",
        failed_approaches=("""python -c "import pandas as pd; pd.Series([1]).iteritems()" """, """python -c "import pandas as pd; pd.DataFrame({'a': [1]}).iteritems(axis=1)" """),
        fix="cd /w && sed -i 's/iteritems/items/g' app.py", verify="cd /w && python app.py",
        root_cause="iteritems was deprecated in pandas 1.5 and removed in 2.0. items() is the same iterator under the name that Series and DataFrame share with dict.",
        steps=("Replace .iteritems() with .items().", "Run the code with python -W error::FutureWarning on pandas 1.5 first to find every use of removed APIs."),
        tags=("python", "pandas", "pandas2", "removed-api"), message="object has no attribute 'iteritems'",
    ),
    from_probe(
        "py-pandas2-datetime-attribute", category="api_contract", error_type="AttributeError", runtime=PY312,
        summary="pandas 2.0 removed pd.datetime, which only re-exported the standard library class, so code that called pd.datetime.now() fails with an AttributeError.",
        context="Upgrading code that used pd.datetime to pandas 2.",
        extra_setup=r"""mkdir -p /w && printf 'import pandas as pd\nprint(pd.datetime.now().year > 2000)\n' > /w/app.py""", failing="cd /w && python app.py 2>&1",
        failed_approaches=("""python -c "import pandas as pd; pd.datetime" """, """python -c "from pandas import datetime" """),
        fix=r"""cd /w && printf 'from datetime import datetime\nprint(datetime.now().year > 2000)\n' > app.py""", verify="cd /w && python app.py",
        root_cause="pandas.datetime was an accident of imports: it exposed datetime.datetime. It was deprecated in 1.0 and removed in 2.0, so the class has to come from the standard library.",
        steps=("Import it: from datetime import datetime.", "For timestamps in pandas use pd.Timestamp.now() or pd.to_datetime."),
        tags=("python", "pandas", "pandas2", "removed-api"), message="has no attribute 'datetime'",
    ),
    from_probe(
        "py-sklearn-load-boston-removed", category="api_contract", error_type="ImportError", runtime=PY312,
        summary="scikit-learn 1.2 removed load_boston for ethical reasons, so an import that older tutorials use fails with an ImportError that explains it.",
        context="Running a tutorial or course notebook that loads the Boston housing dataset on a current scikit-learn.",
        extra_setup=r"""mkdir -p /w && printf 'from sklearn.datasets import load_boston\nprint(load_boston().data.shape)\n' > /w/app.py""", failing="cd /w && python app.py 2>&1",
        failed_approaches=("""python -c "from sklearn.datasets import load_boston" """, """python -c "import sklearn.datasets as d; d.load_boston" """),
        fix=r"""cd /w && printf 'from sklearn.datasets import load_diabetes\nprint(load_diabetes().data.shape)\n' > app.py""", verify="cd /w && python app.py",
        root_cause="The Boston dataset contains a column built on a racial assumption, so scikit-learn deprecated it in 1.0 and removed it in 1.2. It is not coming back; use another dataset.",
        steps=("Use fetch_california_housing (downloads on first use) for a regression example, or load_diabetes, which ships with the package.", "Pinning scikit-learn<1.2 works, but locks the project to an old release."),
        tags=("python", "scikit-learn", "removed-dataset"), message="`load_boston` has been removed",
    ),
    from_probe(
        "py-httpx028-starlette-testclient", category="dependency", error_type="TypeError", runtime=PY312,
        summary="Starlette's TestClient in releases before 0.37 passes an app argument that httpx 0.28 removed, so building a TestClient fails with a TypeError.",
        context="Running the tests of a FastAPI or Starlette app after pip resolved httpx 0.28 next to an older Starlette.",
        failed_approaches=("""python -c "import httpx; httpx.Client(app=None)" """, """python -c "from starlette.applications import Starlette; from starlette.testclient import TestClient; TestClient(Starlette(), base_url='http://t')" """),
        fix="pip install -q -U starlette",
        verify="""python -c "from starlette.applications import Starlette; from starlette.testclient import TestClient; TestClient(Starlette()); print('ok')" """,
        root_cause="httpx 0.28 dropped its app shortcut, which Starlette's TestClient used before it moved to an explicit transport in 0.37. An old Starlette (often an old FastAPI pin) next to a new httpx cannot build the client.",
        steps=("Upgrade Starlette (and FastAPI, which pins it) to a release that no longer needs the removed argument.", "Or pin httpx<0.28 until you can."),
        tags=("python", "starlette", "fastapi", "httpx", "version-conflict"), message="unexpected keyword argument 'app'",
    ),
    from_probe(
        "py-poetry2-lock-out-of-sync", category="tooling", error_type="poetry.lock out of date", runtime=PY312, memory="2g",
        summary="poetry install stops when pyproject.toml has changed since poetry.lock was written and tells you to run poetry lock.",
        context="Installing a project in CI after someone edited the dependencies without committing the new lock file.",
        failing="cd /tmp/demo && poetry install 2>&1",
        failed_approaches=("cd /tmp/demo && poetry install --no-root 2>&1", "cd /tmp/demo && poetry check --lock 2>&1"),
        fix="cd /tmp/demo && poetry lock && poetry install --no-root", verify="cd /tmp/demo && poetry check --lock",
        root_cause="poetry.lock records a hash of the dependency section of pyproject.toml. When they disagree, installing from the lock would not install what pyproject asks for, so Poetry refuses instead of guessing.",
        steps=("Run poetry lock and commit the new poetry.lock.", "Add poetry check --lock to CI so the mismatch fails the pull request that caused it."),
        tags=("python", "poetry", "lockfile", "ci"), message="Run `poetry lock` to fix the lock file",
    ),
    from_probe(
        "py-uv-locked-lockfile-stale", category="tooling", error_type="uv.lock needs to be updated", runtime=PY312,
        summary="uv sync --locked fails when uv.lock no longer matches pyproject.toml, because --locked forbids updating the lock file.",
        context="Installing a uv project in CI with --locked after dependencies changed without a new lock file.",
        failing="cd /tmp/demo && uv sync --locked 2>&1",
        failed_approaches=("cd /tmp/demo && uv lock --check 2>&1", "cd /tmp/demo && uv sync --frozen --locked 2>&1"),
        fix="cd /tmp/demo && uv lock && uv sync --locked", verify="cd /tmp/demo && uv sync --locked && echo in-sync",
        root_cause="--locked means: install exactly what uv.lock says and fail if it is stale. The failure is the check working; the lock file has to be regenerated by whoever changed the dependencies.",
        steps=("Run uv lock and commit uv.lock.", "Use --frozen only if you want to install the lock as it is without checking it against pyproject.", "Run uv lock --check in CI to catch it early."),
        tags=("python", "uv", "lockfile", "ci"), message="needs to be updated, but `--locked` was provided",
    ),
    from_probe(
        "py-pip-conflicting-dependencies", category="dependency", error_type="ResolutionImpossible", runtime=PY312,
        summary="pip refuses to install two requirements whose dependencies cannot both be satisfied and prints Cannot install ... because these package versions have conflicting dependencies.",
        context="Pinning an old requests next to a recent urllib3 in a requirements file.",
        failed_approaches=("""pip install "requests==2.25.1" "urllib3>=2" --upgrade-strategy eager 2>&1""", """pip install "requests==2.25.1" "urllib3>=2" --dry-run 2>&1"""),
        fix="""pip install -q "requests>=2.31" "urllib3>=2" """, verify="""python -c "import requests, urllib3; print(requests.__version__, urllib3.__version__)" """,
        root_cause="requests 2.25.1 declares urllib3<1.27, so no urllib3 2.x can coexist with it. pip's resolver now fails instead of installing a broken set, and its message names the two requirements.",
        steps=("Loosen or remove the pin that conflicts (here requests), or lower the other requirement (urllib3<1.27).", "Read the lines after the error: they list which package requires which range."),
        tags=("python", "pip", "dependency-resolver", "version-conflict"), message="conflicting dependencies",
    ),
)

TASKS += (
    from_probe(
        "py-pip-no-matching-distribution", category="dependency", error_type="No matching distribution found", runtime=PY312, memory="512m",
        summary="pip install fails with Could not find a version that satisfies the requirement and No matching distribution found when the pinned version does not exist or does not support this Python.",
        context="Installing a requirements file with a pin that was mistyped, yanked, or published only for other Python versions.",
        failed_approaches=("pip install --upgrade pip >/dev/null 2>&1; pip install requests==999.0.0 2>&1", "pip install --index-url https://pypi.org/simple requests==999.0.0 2>&1"),
        fix="pip install requests==2.32.3", verify="""python -c "import requests; print(requests.__version__)" """,
        root_cause="pip lists the versions it can see for this interpreter in the message. A pin to a version that is not among them cannot be satisfied, and upgrading pip or naming the official index changes nothing. The same message appears when every release requires a newer Python than the one running.",
        steps=("Read the versions pip lists after from versions and pin one of them, or drop the pin.", "If the list is empty or ends too early, check the Python version (python --version) against the package's supported versions, and the index URL if you use a private mirror."),
        tags=("pip", "requirements", "versions"), message="Could not find a version that satisfies the requirement",
    ),
)

TASKS += (
    from_probe(
        "py-pip-externally-managed-environment", category="tooling", error_type="externally-managed-environment", runtime={"name": "python", "version": "3.11"}, memory="2g",
        summary="pip install fails with error: externally-managed-environment on Debian 12, Ubuntu 23.04 and later, and recent Fedora, because the system Python is managed by the OS package manager.",
        context="Running pip install against the system Python of a recent Debian or Ubuntu image, or machine, outside a virtual environment.",
        failed_approaches=("pip install --upgrade pip 2>&1", "pip install --user requests 2>&1"),
        fix="apt-get install -y -qq python3-venv >/dev/null && python3 -m venv /tmp/venv && /tmp/venv/bin/pip install requests", verify="""/tmp/venv/bin/python -c "import requests; print(requests.__version__)" """,
        root_cause="Distributions mark their Python as externally managed (PEP 668) with an EXTERNALLY-MANAGED file, so that pip does not overwrite files the system packages own. pip refuses every install into that interpreter, including upgrading pip and --user installs.",
        steps=("Create a virtual environment and install into it: python3 -m venv .venv && .venv/bin/pip install <package>. On Debian and Ubuntu that needs the python3-venv package.", "For a command-line tool use pipx; for a system-wide package use the distribution's own (apt install python3-<name>). --break-system-packages exists but can break the system tools."),
        tags=("pip", "pep668", "venv", "debian", "ubuntu", "docker"), message="externally-managed-environment",
    ),
)
