from .probes import from_probe

PY312 = {"name": "python", "version": "3.12"}
PY311 = {"name": "python", "version": "3.11"}

TASKS = (
    from_probe(
        "py-numpy2-float_", category="api_contract", error_type="AttributeError", runtime=PY312, message="`np.float_` was removed",
        summary="NumPy 2.0 removed the np.float_ alias, so code written for NumPy 1.x that calls np.float_ fails with an AttributeError after the upgrade.",
        context="Running a script that was written against NumPy 1.x after pip installed NumPy 2.0.",
        extra_setup="mkdir -p /w && printf 'import numpy as np\\nprint(np.float_(1))\\n' > /w/app.py", failing="cd /w && python app.py 2>&1",
        failed_approaches=('python -c "import numpy as np; np.float"', 'python -c "import numpy as np; print(np.float_)"'),
        fix="cd /w && sed -i 's/np.float_/np.float64/g' app.py", verify="cd /w && python app.py",
        root_cause="NumPy 2.0 removed the aliases that duplicated a name with a trailing underscore or a Python type (np.float_, np.NaN, np.Inf and others). np.float64 is the same type under its real name.",
        steps=("Replace np.float_ with np.float64 wherever it is used.", "If a dependency is the one calling np.float_, upgrade it to a release that supports NumPy 2, or pin numpy<2 until it does."),
        tags=("python", "numpy", "numpy2", "removed-alias"),
    ),
    from_probe(
        "py-numpy2-nan", category="api_contract", error_type="AttributeError", runtime=PY312, message="`np.NaN` was removed",
        summary="NumPy 2.0 removed np.NaN, np.NAN and np.Inf, so code that spelled the not-a-number constant that way fails after the upgrade.",
        context="Running data-cleaning code written for NumPy 1.x on NumPy 2.0.",
        extra_setup="mkdir -p /w && printf 'import numpy as np\\nprint(np.NaN)\\n' > /w/app.py", failing="cd /w && python app.py 2>&1",
        failed_approaches=('python -c "import numpy as np; np.NAN"', 'python -c "import numpy as np; np.Nan"'),
        fix="cd /w && sed -i 's/np.NaN/np.nan/g' app.py", verify="cd /w && python app.py",
        root_cause="NumPy 2.0 kept one lowercase spelling for each constant: np.nan and np.inf. The capitalised aliases were removed.",
        steps=("Use np.nan and np.inf.", "Search the whole project for NaN and Inf spelled with capitals, including notebooks and dependencies you vendor."),
        tags=("python", "numpy", "numpy2", "removed-alias"),
    ),
    from_probe(
        "py-jinja31-markup", category="api_contract", error_type="ImportError", runtime=PY312,
        summary="Jinja2 3.1 no longer re-exports Markup and escape, so an import from jinja2 that worked on 3.0 fails with ImportError.",
        context="Running an older Flask or Jinja2 extension after Jinja2 was upgraded to 3.1.",
        extra_setup="mkdir -p /w && printf 'from jinja2 import Markup\\nprint(Markup(\"<b>x</b>\"))\\n' > /w/app.py", failing="cd /w && python app.py 2>&1",
        failed_approaches=('python -c "from jinja2 import escape"', 'python -c "import jinja2; jinja2.Markup"'),
        fix="cd /w && sed -i 's/from jinja2 import Markup/from markupsafe import Markup/' app.py", verify="cd /w && python app.py",
        root_cause="Jinja2 3.1 removed the names it had re-exported from MarkupSafe (Markup, escape). They have always lived in the markupsafe package, which Jinja2 depends on.",
        steps=("Import Markup and escape from markupsafe.", "If a third-party package does the old import, upgrade it; pinning Jinja2<3.1 is only a stopgap."),
        tags=("python", "jinja2", "markupsafe", "removed-reexport"),
    ),
    from_probe(
        "py-django4-force-text", category="api_contract", error_type="ImportError", runtime=PY312,
        summary="Django 4.0 removed force_text and smart_text from django.utils.encoding, so imports written for Django 3.x fail with ImportError.",
        context="Upgrading a project, or one of its third-party apps, from Django 3.2 to 4.x.",
        extra_setup="mkdir -p /w && printf 'from django.utils.encoding import force_text\\nprint(force_text(b\"ok\"))\\n' > /w/app.py", failing="cd /w && python app.py 2>&1",
        failed_approaches=('python -c "from django.utils.encoding import force_unicode"', 'python -c "from django.utils import encoding; print(encoding.force_text)"'),
        fix="cd /w && sed -i 's/force_text/force_str/g' app.py", verify="cd /w && python app.py",
        root_cause="Django 3.0 deprecated force_text, smart_text and the other *_text helpers in favour of force_str and smart_str, and Django 4.0 removed them.",
        steps=("Replace force_text with force_str and smart_text with smart_str.", "If the call comes from a third-party app, upgrade that app to a release that supports Django 4."),
        tags=("python", "django", "django4", "removed-api"),
    ),
    from_probe(
        "py-werkzeug3-url-quote", category="dependency", error_type="ImportError", runtime=PY312,
        summary="Flask 2.2.2 and older import url_quote from werkzeug.urls, which Werkzeug 3.0 removed, so importing flask fails when pip resolves a newer Werkzeug.",
        context="Installing or running an application that pins an old Flask but not Werkzeug.",
        failed_approaches=('python -c "from werkzeug.urls import url_quote"', 'python -c "from werkzeug.urls import url_encode"'),
        fix="pip install -q -U flask", verify='python -c "import flask; print(flask.__version__)"',
        root_cause="Flask 2.2.2 and earlier did not cap Werkzeug, and called url_quote, which Werkzeug 3.0 removed. Newer Flask releases no longer use it.",
        steps=("Upgrade Flask to 2.3 or later.", "If you cannot upgrade, pin werkzeug<3 in the same requirements file as Flask."),
        tags=("python", "flask", "werkzeug", "version-conflict"),
    ),
    from_probe(
        "py-httpx028-proxies", category="dependency", error_type="TypeError", runtime=PY312,
        summary="httpx 0.28 removed the proxies argument, so OpenAI client releases that still pass it to httpx.Client fail on construction with a TypeError.",
        context="Creating an OpenAI client after pip resolved the newest httpx next to an older openai package.",
        failed_approaches=('python -c "import httpx; httpx.Client(proxies=\'http://localhost:3128\')"', 'python -c "import httpx; httpx.Client(proxies={})"'),
        fix="pip install -q -U openai", verify='python -c "import openai; openai.OpenAI(api_key=\'x\'); print(\'ok\')"',
        root_cause="httpx 0.28 dropped the deprecated proxies argument in favour of proxy and mounts. openai releases before 1.56 and several other SDKs still passed proxies, and their requirements did not cap httpx.",
        steps=("Upgrade the SDK that builds the client (openai 1.56 or later stopped passing proxies).", "Alternatively pin httpx<0.28 until every package that calls it is upgraded."),
        tags=("python", "httpx", "openai", "version-conflict"),
    ),
    from_probe(
        "py-pyyaml541-cython3", category="dependency", error_type="AttributeError", runtime=PY311,
        summary="Installing PyYAML 5.4.1 from source fails at build time with an AttributeError about cython_sources, because its build now pulls Cython 3.",
        context="Running pip install on a requirements file that pins pyyaml==5.4.1, for example in an old Docker image or CI job.",
        failing="pip install pyyaml==5.4.1 2>&1",
        failed_approaches=('pip install -q setuptools wheel && pip install pyyaml==5.4.1 2>&1', 'pip install -q cython==0.29.36 && pip install pyyaml==5.4.1 2>&1'),
        fix="pip install -q pyyaml", verify='python -c "import yaml; print(yaml.__version__)"',
        root_cause="PyYAML 5.4.1 has no wheel for this Python, so pip builds it in an isolated environment that installs the newest Cython. Cython 3 broke the old setup, and a Cython installed in your own environment is not seen by that isolated build.",
        steps=("Install a PyYAML release that publishes wheels for your Python (6.0 or later).", "If you must stay on 5.4.1, install Cython<3 and then run pip install pyyaml==5.4.1 --no-build-isolation, so that the build uses the Cython you installed."),
        tags=("python", "pyyaml", "cython", "build-isolation"),
    ),
    from_probe(
        "py-pyyaml6-load-loader", category="api_contract", error_type="TypeError", runtime=PY312,
        summary="PyYAML 6.0 made the Loader argument of yaml.load required, so calls that relied on the default fail with a TypeError.",
        context="Running a script written for PyYAML 5 after upgrading to PyYAML 6.",
        extra_setup="mkdir -p /w && printf 'import yaml\\nprint(yaml.load(\"a: 1\"))\\n' > /w/app.py", failing="cd /w && python app.py 2>&1",
        failed_approaches=('python -c "import yaml; yaml.load(\'a: 1\', Loader=None)"', 'pip install -q "pyyaml<6" 2>&1'),
        fix="cd /w && sed -i 's/yaml.load(/yaml.safe_load(/' app.py", verify="cd /w && python app.py",
        root_cause="PyYAML 5.1 deprecated calling yaml.load without a Loader, because the default loader could run arbitrary code, and 6.0 made the argument mandatory.",
        steps=("Use yaml.safe_load for untrusted or plain data.", "Pass Loader=yaml.SafeLoader (or FullLoader when you really need Python tags) if you must keep calling yaml.load."),
        tags=("python", "pyyaml", "removed-default"),
    ),
    from_probe(
        "py-setuptools75-test-command", category="tooling", error_type="invalid command", runtime=PY312,
        summary="Running python setup.py test fails with invalid command 'test' on setuptools 72 and later, which removed the test command.",
        context="A project with a legacy setup.py whose CI still calls python setup.py test.",
        failed_approaches=("cd /w && python setup.py pytest 2>&1", "cd /w && python setup.py nosetests 2>&1"),
        fix="pip install -q pytest && cd /w && printf 'def test_ok():\\n    assert True\\n' > test_ok.py", verify="cd /w && pytest -q",
        root_cause="setuptools deprecated the test command in 41 and removed it in 72. A setup.py is a build script, not a test runner, and calling it directly is deprecated.",
        steps=("Run the tests with pytest (or your runner) directly.", "Move test dependencies to an extra or a requirements file and update the CI job."),
        tags=("python", "setuptools", "setup-py", "removed-command"),
    ),
    from_probe(
        "py-sqlalchemy2-engine-execute", category="api_contract", error_type="AttributeError", runtime=PY312,
        summary="SQLAlchemy 2.0 removed Engine.execute, so code that ran SQL straight on an engine fails with an AttributeError.",
        context="Upgrading an application from SQLAlchemy 1.4 to 2.0.",
        extra_setup="mkdir -p /w && printf 'from sqlalchemy import create_engine\\ne = create_engine(\"sqlite://\")\\nprint(e.execute(\"select 1\").scalar())\\n' > /w/app.py", failing="cd /w && python app.py 2>&1",
        failed_approaches=("python -c \"from sqlalchemy import create_engine; e = create_engine('sqlite://'); e.connect().execute('select 1')\"", "python -c \"from sqlalchemy import create_engine; create_engine('sqlite://', future=False)\""),
        fix="cd /w && printf 'from sqlalchemy import create_engine, text\\ne = create_engine(\"sqlite://\")\\nwith e.connect() as c:\\n    print(c.execute(text(\"select 1\")).scalar())\\n' > app.py",
        verify="cd /w && python app.py",
        root_cause="SQLAlchemy 2.0 removed implicit execution on the engine and requires a Connection, and it no longer accepts a plain string as SQL: text() wraps it.",
        steps=("Open a connection with engine.connect() (or engine.begin() for a transaction).", "Wrap raw SQL in sqlalchemy.text().", "Commit explicitly when you write: connections no longer autocommit."),
        tags=("python", "sqlalchemy", "sqlalchemy2", "removed-api"),
    ),
    from_probe(
        "py-sqlalchemy2-postgres-dialect", category="configuration", error_type="NoSuchModuleError", runtime=PY312, message="Can't load plugin: sqlalchemy.dialects:postgres",
        summary="SQLAlchemy 1.4 removed the postgres:// URL scheme, so a DATABASE_URL that starts with postgres:// (as some hosting platforms provide) fails with NoSuchModuleError.",
        context="Pointing SQLAlchemy at a connection string handed out by a hosting platform.",
        failed_approaches=("python -c \"from sqlalchemy import create_engine; create_engine('postgresql+psycopg2://u:p@h/db')\"", "python -c \"from sqlalchemy import create_engine; create_engine('postgres+psycopg2://u:p@h/db')\""),
        fix="pip install -q psycopg2-binary", verify="python -c \"from sqlalchemy import create_engine; create_engine('postgresql://u:p@h/db'); print('ok')\"",
        root_cause="SQLAlchemy deprecated the postgres dialect name in 1.3 and removed it in 1.4; the dialect is postgresql. The scheme must be rewritten, and a driver such as psycopg2 must be installed for the engine to load it.",
        steps=("Replace the postgres:// prefix with postgresql://, for example with url.replace('postgres://', 'postgresql://', 1).", "Install a driver (psycopg2-binary or psycopg) in the same environment."),
        tags=("python", "sqlalchemy", "postgres", "connection-string"),
    ),
    from_probe(
        "py-torch26-weights-only", category="api_contract", error_type="UnpicklingError", runtime=PY312, memory="4g", message="Weights only load failed",
        summary="PyTorch 2.6 changed torch.load to weights_only=True by default, so loading a checkpoint that contains arbitrary Python objects fails with an UnpicklingError.",
        context="Loading a checkpoint saved with an older PyTorch, or one that stores a custom class, after upgrading to PyTorch 2.6.",
        failed_approaches=("python -c \"import torch\nclass A: pass\ntorch.save(A(), '/tmp/a.pt')\ntorch.load('/tmp/a.pt', weights_only=True)\" 2>&1", "python -c \"import torch\nclass A: pass\ntorch.save(A(), '/tmp/a.pt')\ntorch.load('/tmp/a.pt', mmap=True)\" 2>&1"),
        fix="python -c \"import torch\nclass A: pass\ntorch.save(A(), '/tmp/a.pt')\nprint(type(torch.load('/tmp/a.pt', weights_only=False)).__name__)\"",
        verify="python -c \"import torch; print(torch.__version__)\"",
        root_cause="Unpickling can run arbitrary code, so PyTorch 2.6 made torch.load refuse anything but tensors and a short allowlist unless you opt out. A checkpoint that pickles another class needs either that class allowlisted or weights_only=False.",
        steps=("Only if you trust the file: pass weights_only=False.", "Better: save a state_dict and load it, or allowlist the classes with torch.serialization.add_safe_globals([...]).", "Never use weights_only=False on a checkpoint from an untrusted source."),
        tags=("python", "pytorch", "torch.load", "pickle"),
    ),
    from_probe(
        "py-uv-no-venv", category="tooling", error_type="uv pip install", runtime=PY312,
        summary="uv pip install refuses to run outside a virtual environment, unlike pip, and tells you to create one or pass --system.",
        context="Replacing pip with uv in a Dockerfile or a CI script that has no virtual environment.",
        failed_approaches=("uv add six 2>&1", "uv pip install six --python python3.99 2>&1"),
        fix="uv venv && uv pip install six", verify='.venv/bin/python -c "import six; print(six.__version__)"',
        root_cause="uv pip never installs into a system interpreter by default; it looks for an active or .venv environment and stops when it finds none. That is intentional, to avoid modifying the system Python.",
        steps=("Create an environment first: uv venv, then uv pip install.", "In a throwaway container where installing into the system Python is what you want, pass --system (or set UV_SYSTEM_PYTHON=1).", "For a project with a pyproject.toml, use uv sync or uv add instead of uv pip."),
        tags=("python", "uv", "virtualenv", "docker"),
    ),
)

TASKS += (
    from_probe(
        "py-scipy114-simps", category="api_contract", error_type="ImportError", runtime=PY312,
        summary="SciPy 1.14 removed scipy.integrate.simps, trapz and cumtrapz, so an import written for older SciPy fails with ImportError.",
        context="Running numerical code after upgrading SciPy to 1.14.",
        extra_setup="mkdir -p /w && printf 'from scipy.integrate import simps\\nprint(simps([1, 2, 3]))\\n' > /w/app.py", failing="cd /w && python app.py 2>&1",
        failed_approaches=('python -c "import scipy.integrate as i; i.simps"', 'python -c "from scipy.integrate import simpson, simps"'),
        fix="cd /w && sed -i 's/simps/simpson/g' app.py", verify="cd /w && python app.py",
        root_cause="The simps, trapz and cumtrapz names were deprecated in SciPy 1.12 in favour of simpson, trapezoid and cumulative_trapezoid, and 1.14 removed them.",
        steps=("Use scipy.integrate.simpson (and trapezoid, cumulative_trapezoid).", "Note simpson's keyword is x= and dx=, and its default behaviour for an even number of points differs; check the docs.", "If a dependency imports the old name, upgrade it or pin scipy<1.14."),
        tags=("python", "scipy", "scipy1.14", "removed-api"),
    ),
    from_probe(
        "py-playwright-browsers-missing", category="tooling", error_type="Executable doesn't exist", runtime=PY312, memory="3g",
        summary="Playwright fails to launch Chromium with Executable doesn't exist because pip installs the library but not the browsers; they are downloaded by a separate command.",
        context="Running a Playwright script in a fresh container, CI job or virtual environment.",
        failed_approaches=("""PLAYWRIGHT_BROWSERS_PATH=/tmp/pw python -c "from playwright.sync_api import sync_playwright\nwith sync_playwright() as p:\n    p.chromium.launch()" 2>&1""", """python -c "from playwright.sync_api import sync_playwright\nwith sync_playwright() as p:\n    p.chromium.launch(executable_path='/usr/bin/chromium')" 2>&1"""),
        fix="python -m playwright install --with-deps chromium >/dev/null 2>&1",
        verify="""python -c "from playwright.sync_api import sync_playwright\nwith sync_playwright() as p:\n    b = p.chromium.launch(); print(b.version); b.close()" """,
        root_cause="The playwright package contains the driver and the API. The browser builds it was tested with are fetched by playwright install into a cache, and a slim image also lacks the system libraries Chromium needs, which --with-deps installs.",
        steps=("Run python -m playwright install chromium (add --with-deps in a Debian-based container to install the system libraries).", "In Docker, use the mcr.microsoft.com/playwright/python image, which has them already.", "Cache ~/.cache/ms-playwright in CI to avoid downloading on every run."),
        tags=("python", "playwright", "browsers", "docker"),
    ),
)
