import { test } from "node:test";
import assert from "node:assert/strict";
import { Session } from "../dist/index.js";

// A colony stand-in: it answers searches and records what is reported and published.
function fakeColony({ known = false } = {}) {
  const calls = { reports: [], published: [] };
  return {
    calls,
    publishMode: "ask",
    async search() {
      return known
        ? { fingerprint: "fp1_0000000000000000", hits: [{ trailId: "3f2b8c1e-9a4d-4e2f-8b1a-2c3d4e5f6a7b" }], notice: "", source: "search" }
        : { fingerprint: "fp1_0000000000000000", hits: [], notice: "", source: "search" };
    },
    async report(id, outcome, options) {
      calls.reports.push({ id, outcome, notes: options?.notes });
      return { trailId: id, counted: true, strength: 0.5 };
    },
    async publish(trail) {
      calls.published.push(trail);
      return { trailId: "x", fingerprint: "fp", status: "queued", redactions: {} };
    },
  };
}

const session = (colony) => new Session(colony, { task: "install deps", runtime: "node", runtimeVersion: "22.1.0" });
const success = {
  rootCause: "The lockfile was generated by a newer package manager.",
  steps: ["Regenerate the lockfile with the installed version"],
  verification: { type: "build_success", description: "build passes" },
};

test("one failed attempt and a verified fix are enough to draft a trail", async () => {
  const s = session(fakeColony());
  await s.failed(new Error("ERR_PNPM_OUTDATED_LOCKFILE: lockfile is outdated"), "pnpm install --frozen-lockfile");
  const { draft } = await s.succeeded(success);
  assert.ok(draft);
  assert.equal(draft.effort.failed_attempts, 1);
});

test("no failed attempt means nothing to publish", async () => {
  const { draft } = await session(fakeColony()).succeeded(success);
  assert.equal(draft, null);
});

test("an unverified fix is not drafted", async () => {
  const s = session(fakeColony());
  await s.failed(new Error("Boom: it broke"));
  assert.equal((await s.succeeded({ ...success, verification: { type: "none", description: "n/a" } })).draft, null);
});

test("when the colony already had a trail and the agent never tried it, nothing is drafted", async () => {
  const s = session(fakeColony({ known: true }));
  await s.failed(new Error("Boom: it broke"));
  assert.equal((await s.succeeded(success)).draft, null);
});

test("a trail that worked means nothing new to publish", async () => {
  const colony = fakeColony({ known: true });
  const s = session(colony);
  await s.failed(new Error("Boom: it broke"));
  await s.tried("3f2b8c1e-9a4d-4e2f-8b1a-2c3d4e5f6a7b", "worked");
  assert.equal((await s.succeeded(success)).draft, null);
  assert.equal(colony.calls.reports[0].outcome, "worked");
});

test("a trail that failed makes the agent's own fix a published alternative, with the dead end recorded", async () => {
  const colony = fakeColony({ known: true });
  colony.publishMode = "auto";
  const s = session(colony);
  await s.failed(new Error("Boom: it broke"), "first attempt");
  await s.tried("3f2b8c1e-9a4d-4e2f-8b1a-2c3d4e5f6a7b", "failed", "needs a different flag on arm64");
  const { draft, published } = await s.succeeded(success);
  assert.ok(draft && published);
  const dead = draft.problem.failed_approaches.map((d) => d.approach);
  assert.ok(dead.some((a) => a.includes("3f2b8c1e-9a4d-4e2f-8b1a-2c3d4e5f6a7b")));
  assert.match(JSON.stringify(draft.problem.failed_approaches), /different flag on arm64/);
  assert.equal(colony.calls.published.length, 1);
});
