#!/usr/bin/env bash
# Close ports 80 and 443 of the origin server to everyone except Cloudflare, so that the real address cannot be used to
# skip the proxy (and its cache, rate limits and DDoS protection). It prints an nftables rule set and does NOTHING else:
# read it, then apply it yourself.
#
#   bash deploy/lock-origin.sh                         # prints the rules
#   bash deploy/lock-origin.sh --allow 203.0.113.7     # also let one address through (yours, for testing)
#   bash deploy/lock-origin.sh | sudo nft -f -         # applies them (until the next reboot)
#   sudo nft delete table inet myrmo_origin            # takes them away
#
# The Cloudflare ranges are read from deploy/Caddyfile.myrmo, the same list Caddy trusts for the real client address,
# so there is one list to keep up to date (https://www.cloudflare.com/ips/). Only ports 80 and 443 are touched: SSH
# and everything else stay as they are. Rules are not persistent; to keep them, save the output into /etc/nftables.conf
# or its include directory.
#
# If Caddy runs in a container with published ports, Docker rewrites the destination before the `forward` hook, so the
# rules below match the container's ports; check with `sudo nft list table inet myrmo_origin` that the counters move.
set -euo pipefail

CADDYFILE="${MYRMO_CADDYFILE:-$(dirname "$0")/Caddyfile.myrmo}"
allow=()
while [ $# -gt 0 ]; do
  case "$1" in
    --allow) allow+=("${2:?--allow needs an address}"); shift 2 ;;
    *) echo "usage: lock-origin.sh [--allow <address>]..." >&2; exit 2 ;;
  esac
done

ranges="$(sed -n 's/^[[:space:]]*trusted_proxies static //p' "$CADDYFILE" | head -1)"
[ -n "$ranges" ] || { echo "no 'trusted_proxies static' line in $CADDYFILE" >&2; exit 1; }

v4=(); v6=()
for r in $ranges $(printf '%s\n' "${allow[@]+"${allow[@]}"}"); do
  case "$r" in
    *:*) v6+=("$r") ;;
    *.*) v4+=("$r") ;;
  esac
done
join() { local IFS=,; echo "$*"; }

cat <<RULES
# Generated by deploy/lock-origin.sh from $(basename "$CADDYFILE") on $(date -u +%FT%TZ)
table inet myrmo_origin {
  set allowed4 { type ipv4_addr; flags interval; elements = { $(join "${v4[@]}") } }
  set allowed6 { type ipv6_addr; flags interval; elements = { $(join "${v6[@]}") } }
  chain guard {
    ip saddr @allowed4 accept
    ip6 saddr @allowed6 accept
    counter drop
  }
  chain input   { type filter hook input   priority -10; policy accept; tcp dport { 80, 443 } jump guard; }
  chain forward { type filter hook forward priority -10; policy accept; tcp dport { 80, 443 } jump guard; }
}
RULES
